name: Testing and linting

on: [push, pull_request]

jobs:
  run-busted-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: leafo/gh-actions-lua@v8.0.0
        with:
          luaVersion: "5.1.5"

      - uses: leafo/gh-actions-luarocks@v4.0.0

      - name: install luvit
        run: |
          curl -L https://github.com/luvit/lit/raw/master/get-lit.sh | sh

      - name: install dependencies
        run: |
          luarocks install busted
          eval `luarocks path`
          ./lit install

      - name: test
        run: |
          ./luvit testRunner.lua
  run-luacheck-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: leafo/gh-actions-lua@v8.0.0
        with:
          luaVersion: "5.1.5"

      - uses: leafo/gh-actions-luarocks@v4.0.0

      - name: install luacheck
        run: |
          luarocks install luacheck

      - name: run lints
        run: |
          luacheck ./libs